# Generated by Django 3.2.7 on 2021-10-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorpost',
            options={'ordering': ['-publish']},
        ),
    ]
