# Generated by Django 3.2.7 on 2021-11-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AlterField(
            model_name='authorpost',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images_cover/'),
        ),
    ]
